[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "endstone-mumble-host"
version = "0.2.1.dev4"
description = "One-file MCSV Mumble Server host with automatic runtime installation"
requires-python = ">=3.11"
dependencies = ["endstone>=0.11.0"]

[project.entry-points."endstone"]
mumble_host = "endstone_mumble_host:MumbleHost"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
