import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { unzipSync } from '../web/join/node_modules/fflate/esm/index.mjs';
import { createMCSVClient,prepareInstallation,publicPlan,installOnMCSV,fetchArtifacts,mergePacks,configEdit,backupGroups,installationStatus,packArchive,WHEEL,PACKS } from '../web/join/lib/mcsv-install.js';
const artifactDir=process.env.SLEEPY_TEST_ARTIFACTS;
import { generateKeyPairSync, verify as edVerify } from 'node:crypto';
const licenseKeys=generateKeyPairSync('ed25519');
process.env.SESSION_SECRET='test-session-secret-0123456789abcdef';
process.env.LICENSE_PRIVATE_KEY=licenseKeys.privateKey.export({format:'der',type:'pkcs8'}).toString('base64');
const { licenseMessage } = await import('../web/join/lib/license.js');
const { verifyArtifact, signArtifact } = await import('../web/join/lib/artifact-token.js');
function assertLicense(text,{server='5fb3cecf',port,users=99}){
 const body=JSON.parse(text);
 assert.equal(body.format,'sleepymumla-license-1');assert.equal(body.server,server);assert.equal(body.port,port);assert.equal(body.users,users);
 assert(edVerify(null,licenseMessage(body.server,body.port,body.users,body.issued),licenseKeys.publicKey,Buffer.from(body.signature,'base64')),'license signature invalid');
}
const { BUNDLED, pickRelease, latestEndweave, loadEndweave, endweaveBytes, resetEndweaveCache } = await import('../web/join/lib/endweave.js');
const weaveBytes=Buffer.from('test-endweave');const weaveInfo={...BUNDLED,sha256:createHash('sha256').update(weaveBytes).digest('hex'),size:weaveBytes.length,source:'test'};
const fixture={endweave:{info:weaveInfo,bytes:weaveBytes},wheel:Buffer.from('test-wheel'),packs:Object.fromEntries(PACKS.map(p=>[p.type,{'manifest.json':Buffer.from(JSON.stringify({header:{uuid:p.uuid,version:[2,15,44]}})),'test.txt':Buffer.from('test')}]))};
const required=['server_overview','files_list','files_read','files_read_many','files_read_base64','files_upload_base64','files_fetch_url','files_decompress','files_write','files_edit','files_compress','files_delete','power_action','domain_info'];
function server({state='offline',permission=true,world='Bedrock level'}={}){
 const files=new Map([['/server.properties','level-name='+world+'\nserver-port=10459\n'],['/worlds/'+world+'/world_behavior_packs.json','[{"pack_id":"other-bp","version":[1,0,0],"extra":true}]'],['/worlds/'+world+'/world_resource_packs.json','[]'],['/plugins/mumble_host/config.toml','# keep this\n[mumble]\nport = 18655 # voice\nusers = 17\n[voice]\nmax_range = 150\n']]);
 const dirs=new Set(['/','/worlds','/worlds/'+world,'/plugins','/plugins/mumble_host','/behavior_packs','/resource_packs']);const calls=[];
 const info={id:'test-server',name:'My server',game:'minecraft-bedrock',server_type:'endstone',port:10459,ports:[10459,18655,27220],status:'active',pelican_identifier:'5fb3cecf'};
 const listing=path=>{const prefix=path==='/'?'/':path+'/';const items=new Map();for(const dir of dirs)if(dir.startsWith(prefix)&&dir!==path&&!dir.slice(prefix.length).includes('/'))items.set(dir.slice(prefix.length),{name:dir.slice(prefix.length),is_file:false});for(const [file,data]of files)if(file.startsWith(prefix)&&!file.slice(prefix.length).includes('/'))items.set(file.slice(prefix.length),{name:file.slice(prefix.length),is_file:true,size:Buffer.byteLength(data)});return {files:[...items.values()]};};
 const client={catalog:async()=>({tools:required.map(name=>({name,allowed:permission||['server_overview'].includes(name),applicable:true}))}),call:async(name,args={})=>{calls.push({name,args});switch(name){case 'domain_info':return {node_hostname:'sv7.mcsv.me'};case 'server_overview':return {info,runtime:{current_state:state}};case 'files_list':return listing(args.directory);case 'files_read':assert(files.has(args.path),'read missing '+args.path);return {content:String(files.get(args.path)),truncated:false};case 'files_read_base64':return {content_base64:Buffer.from(files.get(args.path)).toString('base64')};case 'files_read_many':return {files:args.paths.map(path=>({path,content:files.has(path)?String(files.get(path)):undefined,...(!files.has(path)?{error:'File not found'}:{})}))};case 'files_compress':assert(args.files.every(file=>!file.includes('/')),'MCSV compression only accepts filenames in one folder');assert(args.files.every(file=>files.has((args.root==='/'?'':args.root)+'/'+file)||dirs.has((args.root==='/'?'':args.root)+'/'+file)));return {success:true,path:(args.root==='/'?'':args.root)+'/'+args.name};case 'files_delete':for(const file of args.files)files.delete(args.root+'/'+file);return {success:true};case 'files_upload_base64':files.set(args.path,Buffer.from(args.content_base64,'base64'));dirs.add(args.path.slice(0,args.path.lastIndexOf('/'))||'/');return {success:true};case 'files_decompress':for(const [path,bytes] of Object.entries(unzipSync(files.get('/'+args.file)))){files.set('/'+path,Buffer.from(bytes));let parent=path.slice(0,path.lastIndexOf('/'));while(parent){dirs.add('/'+parent);parent=parent.includes('/')?parent.slice(0,parent.lastIndexOf('/')):'';}}return {success:true};case 'files_edit':{let content=String(files.get(args.path));for(const edit of args.edits){assert.equal(content.split(edit.old_string).length,2);content=content.replace(edit.old_string,edit.new_string);}files.set(args.path,content);return {success:true};}case 'files_write':files.set(args.path,args.content);return {success:true};case 'power_action':return {success:true};default:throw Error(name);}}};return {client,calls,files,dirs,info};
}
const current=server();const plan=await prepareInstallation(current.client);assert.deepEqual(plan.ports,[18655,27220]);assert.equal(plan.world,'Bedrock level');assert.equal(plan.installation.status,'absent');assert(!('internal' in publicPlan(plan)));
const components=[];const result=await installOnMCSV(current.client,{serverId:'test-server',world:'Bedrock level',voicePort:27220,start:false},async()=>fixture,async()=>true,async component=>components.push(component));assert.deepEqual(components,['addon','plugin']);assert.equal(result.installed,true);assert(result.backup);assert.equal(result.backups.length,2);assert.deepEqual(current.calls.filter(c=>c.name==='files_compress').map(c=>c.args.root),['/worlds/Bedrock level','/plugins/mumble_host']);assert.equal(current.files.get('/plugins/'+WHEEL).toString(),'test-wheel');assert.equal(current.calls.find(c=>c.name==='power_action').args.action,'start');const bp=JSON.parse(current.files.get('/worlds/Bedrock level/world_behavior_packs.json'));assert.deepEqual(bp[0],{pack_id:'other-bp',version:[1,0,0],extra:true});assert.equal(bp[1].pack_id,PACKS[0].uuid);assert.match(current.files.get('/plugins/mumble_host/config.toml'),/port = 27220 # voice/);assert.match(current.files.get('/plugins/mumble_host/config.toml'),/users = 17/);assert.match(current.files.get('/plugins/mumble_host/config.toml'),/max_range = 150/);assert.equal(result.licensed,true);assertLicense(current.files.get('/plugins/mumble_host/license.json'),{port:27220});
current.files.delete('/behavior_packs/SleepyMumla_BP/test.txt');
await installOnMCSV(current.client,{serverId:'test-server',world:'Bedrock level',voicePort:27220,start:true,reinstall:true},async()=>fixture);assert.equal(JSON.parse(current.files.get('/worlds/Bedrock level/world_behavior_packs.json')).length,2);assert.equal(current.calls.filter(c=>c.name==='files_decompress').length,2);assert.equal(current.calls.filter(c=>c.name==='power_action').length,2);assert.equal(current.files.get('/behavior_packs/SleepyMumla_BP/test.txt').toString(),'test');
for(const [options,body,code]of [[{state:'starting'},{},'server_running'],[{permission:false},{},'permission'],[{}, {voicePort:10459},'invalid_port'],[{}, {serverId:'different'},'server_changed']]){const s=server(options);await assert.rejects(installOnMCSV(s.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655,start:false,...body},async()=>fixture),e=>e.code===code);assert(!s.calls.some(c=>['files_edit','files_write','files_upload_base64','power_action'].includes(c.name)));}
assert.deepEqual(backupGroups(['worlds/Bedrock level/world_behavior_packs.json','worlds/Bedrock level/world_resource_packs.json','plugins/mumble_host/config.toml','plugins/a.whl','behavior_packs/SleepyMumla_BP','resource_packs/SleepyMumla_RP']),[{root:'/worlds/Bedrock level',files:['world_behavior_packs.json','world_resource_packs.json']},{root:'/plugins/mumble_host',files:['config.toml']},{root:'/plugins',files:['a.whl']},{root:'/behavior_packs',files:['SleepyMumla_BP']},{root:'/resource_packs',files:['SleepyMumla_RP']}]);
const failedBackup=server();const callBeforeFailure=failedBackup.client.call;failedBackup.client.call=async(name,args)=>{if(name==='files_compress'){const error=new Error('rejected');const {MCSVError}=await import('../web/join/lib/mcsv.js');throw new MCSVError('rejected',400);}return callBeforeFailure(name,args);};await assert.rejects(installOnMCSV(failedBackup.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655,start:false},async()=>fixture),e=>e.code==='backup_failed'&&e.stage==='backup'&&e.partial===false);assert(!failedBackup.calls.some(c=>['files_upload_base64','files_edit','files_write','power_action'].includes(c.name)));
const invalid=server();invalid.files.set('/worlds/Bedrock level/world_behavior_packs.json','bad-json');await assert.rejects(prepareInstallation(invalid.client),e=>e.code==='invalid_pack_list');
const symlink=server();const previous=symlink.client.call;symlink.client.call=async(name,args)=>name==='files_list'?{files:[{name:'worlds',is_file:false,is_symlink:true}]}:previous(name,args);await assert.rejects(prepareInstallation(symlink.client),e=>e.code==='unsafe_layout');
assert.throws(()=>createMCSVClient('bad'),e=>e.code==='invalid_key');let endpoint;const client=createMCSVClient('mcsv_testkey0000',async(url,options)=>{endpoint=url;assert.equal(options.redirect,'error');assert.equal(options.headers.Authorization,'Bearer mcsv_testkey0000');return {ok:false,status:403};});await assert.rejects(client.call('files_list'),e=>e.code==='permission');assert.equal(endpoint,'https://api.mcsv.me/api/v1/tools/files_list');
assert.throws(()=>mergePacks('{}',PACKS[0].uuid),e=>e.code==='invalid_pack_list');assert.throws(()=>configEdit('[mumble]\nport="bad"\n',18655),e=>e.code==='invalid_config');
await assert.rejects(fetchArtifacts(async()=>({ok:true,arrayBuffer:async()=>Buffer.from('tampered')}),'https://example.invalid/'),e=>e.code==='artifact_integrity');
if(artifactDir){const assets=await fetchArtifacts(async url=>({ok:true,arrayBuffer:async()=>readFile(artifactDir+'/'+url.split('/').at(-1))}),'https://example.invalid/');assert.equal(assets.wheel.length,1060970);assert(Object.keys(assets.packs.behavior).length>10);assert(Object.keys(assets.packs.resource).length>100);assert.equal(createHash('sha256').update(assets.wheel).digest('hex'),'1299a4ac0acce147238d46482ce9779d03148e1b6007f9c115d854640040fb67');}
console.log('PASS installer: preserves packs/config, repeat install, permissions/offline/ports, tampering, pinned release assets');

const running=server({state:'running'});const live=await installOnMCSV(running.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);assert.equal(live.powerAction,'restart');assert.equal(running.calls.at(-1).args.action,'restart');assert(running.calls.findIndex(c=>c.name==='power_action')>running.calls.findIndex(c=>c.name==='files_upload_base64'));

const pending={serverId:'test-server',host:'sv7.mcsv.me',voicePort:18655,action:'restart',previousUptime:600000,requestedAt:10000};
const statusClient={call:async(name)=>name==='server_overview'?{info:{id:'test-server'},runtime:{current_state:'running',resources:{uptime:3000}}}:name==='files_list'?{files:[{name:'host-status.txt',is_file:true}]}:{content:'stage=running port=18655 pid=2'}};
assert.equal((await installationStatus(statusClient,pending,16000)).joinUrl,'/join#mumble://sv7.mcsv.me:18655/');
const oldRuntime={call:async(name,args)=>name==='server_overview'?{info:{id:'test-server'},runtime:{current_state:'running',resources:{uptime:607000}}}:statusClient.call(name,args)};assert.equal((await installationStatus(oldRuntime,pending,16000)).ready,false);
assert.equal((await installationStatus(statusClient,{...pending,voicePort:27220},16000)).ready,false);
await assert.rejects(installationStatus(statusClient,pending,1000000),e=>e.code==='status_expired');

const detected=await prepareInstallation(current.client);assert.equal(detected.installation.status,'current');assert.equal(detected.voicePort,27220);
const beforeRepeat=current.calls.length;await assert.rejects(installOnMCSV(current.client,{serverId:'test-server',world:'Bedrock level',voicePort:27220},async()=>fixture),e=>e.code==='reinstall_confirmation');assert(!current.calls.slice(beforeRepeat).some(c=>['files_upload_base64','power_action'].includes(c.name)));
const old=server();await installOnMCSV(old.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);
old.files.delete('/plugins/'+WHEEL);old.files.set('/plugins/endstone_mumble_host-0.5.4-py3-none-any.whl',Buffer.from('old-wheel'));
for(const p of PACKS)old.files.set('/'+p.type+'_packs/'+p.folder+'/manifest.json',JSON.stringify({header:{uuid:p.uuid,version:[2,15,38]}}));
assert.equal((await prepareInstallation(old.client)).installation.status,'update');
await installOnMCSV(old.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);
assert(!old.files.has('/plugins/endstone_mumble_host-0.5.4-py3-none-any.whl'));assert(old.calls.some(c=>c.name==='files_compress'&&c.args.files.includes('endstone_mumble_host-0.5.4-py3-none-any.whl')));assert.equal((await prepareInstallation(old.client)).installation.status,'current');
const freshDenied=server();await assert.rejects(installOnMCSV(freshDenied.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture,async fresh=>{assert.equal(fresh.installation.present,false);throw Error('payment_required');}),/payment_required/);assert(!freshDenied.calls.some(c=>['files_compress','files_upload_base64','power_action'].includes(c.name)));
// Install refuses when licensing is not configured or the server has no identifier, before any mutation.
const noKey=server();const savedKey=process.env.LICENSE_PRIVATE_KEY;delete process.env.LICENSE_PRIVATE_KEY;
await assert.rejects(installOnMCSV(noKey.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture),e=>e.code==='license_unavailable'&&e.stage==='license');
assert(!noKey.calls.some(c=>c.name==='power_action'));process.env.LICENSE_PRIVATE_KEY=savedKey;
const noId=server();noId.info.pelican_identifier=undefined;
await assert.rejects(installOnMCSV(noId.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture),e=>e.code==='license_unavailable');
console.log('PASS license binding: signed license written and verified, missing key or identifier blocks install');

old.files.set('/behavior_packs/SleepyMumla_BP/manifest.json',JSON.stringify({header:{uuid:PACKS[0].uuid,version:[9,0,0]}}));await assert.rejects(prepareInstallation(old.client),e=>e.code==='newer_version');
console.log('PASS installation detection: absent/current/old versions, confirmation, old wheel backup/removal, fresh authorization and no downgrade');

const timeouts=[],originalTimeout=AbortSignal.timeout;AbortSignal.timeout=ms=>{timeouts.push(ms);return originalTimeout(ms);};try{const timed=createMCSVClient('mcsv_test_key_12345',async()=>({ok:true,json:async()=>({ok:true,result:{success:true}})}));await timed.call('files_upload_base64',{path:'/test.zip',content_base64:'AA=='});await timed.call('files_decompress',{root:'/',file:'test.zip'});await timed.call('server_overview');assert.deepEqual(timeouts,[120000,120000,30000]);}finally{AbortSignal.timeout=originalTimeout;}const bodyTimeout=createMCSVClient('mcsv_test_key_12345',async()=>({ok:true,json:async()=>{const error=Error('timeout');error.name='TimeoutError';throw error;}}));await assert.rejects(bodyTimeout.call('files_decompress'),e=>e.code==='timeout'&&e.operation==='files_decompress');console.log('PASS MCSV timeouts: long file operations get 120 seconds, reads keep 30 seconds, response-body timeouts retain operation');

const direct=server();const directCall=direct.client.call;direct.client.call=async(name,args)=>{if(name==='files_fetch_url'){direct.calls.push({name,args});const url=new URL(args.url);assert.equal(url.origin,'https://sleepyvoice-join.vercel.app');assert(verifyArtifact(Object.fromEntries(url.searchParams)),'artifact link must be signed');const kind=url.searchParams.get('kind');if(kind==='endweave')assert.equal(url.searchParams.get('sha'),weaveInfo.sha256);const bytes=kind==='endweave'?weaveBytes:kind==='plugin'?fixture.wheel:packArchive(fixture,{behavior:url.searchParams.get('behavior'),resource:url.searchParams.get('resource')});direct.files.set((args.directory==='/'?'':args.directory)+'/'+args.filename,bytes);return {success:true};}return directCall(name,args);};
await installOnMCSV(direct.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>({...fixture,transferOrigin:'https://sleepyvoice-join.vercel.app'}));assert.equal(direct.calls.filter(c=>c.name==='files_fetch_url').length,3);assert(!direct.calls.some(c=>c.name==='files_upload_base64'));
assert.throws(()=>packArchive(fixture,{behavior:'../plugins'}),e=>e.code==='unsafe_layout');
const damaged=server();const damagedCall=damaged.client.call;damaged.client.call=async(name,args)=>name==='files_fetch_url'?{}:name==='files_read_base64'?{content_base64:Buffer.from('bad').toString('base64')}:damagedCall(name,args);await assert.rejects(installOnMCSV(damaged.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>({...fixture,transferOrigin:'https://sleepyvoice-join.vercel.app'})),e=>e.code==='verification_failed'&&e.stage==='packs_upload');assert(!damaged.calls.some(c=>['files_decompress','power_action'].includes(c.name)));
console.log('PASS direct downloads: no Base64 upload, path validation, corrupt download rejected before extraction/restart');

// Endweave: installed with the system, replaced when older, never downgraded, reported per part.
assert.equal(current.files.get('/plugins/'+BUNDLED.name).toString(),'test-endweave');
const firstPlan=await prepareInstallation(current.client);assert.deepEqual(firstPlan.installation.parts,{plugin:'current',addon:'current',endweave:'current',license:'valid'});assert.equal(firstPlan.installation.latest.endweave.version,'0.5.1');assert.equal(firstPlan.installation.latest.endweave.project,'https://github.com/EndstoneMC/endweave');
const weaveOld=server();await installOnMCSV(weaveOld.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);
weaveOld.files.delete('/plugins/'+BUNDLED.name);weaveOld.files.set('/plugins/endstone_endweave-0.4.3-py3-none-any.whl',Buffer.from('old-weave'));
const oldPlan=await prepareInstallation(weaveOld.client);assert.equal(oldPlan.installation.status,'update');assert.equal(oldPlan.installation.parts.endweave,'update');assert.deepEqual(oldPlan.installation.endweaveVersions,['0.4.3']);
const updated=await installOnMCSV(weaveOld.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);assert.equal(updated.endweaveVersion,'0.5.1');
assert(!weaveOld.files.has('/plugins/endstone_endweave-0.4.3-py3-none-any.whl'));assert(weaveOld.calls.some(c=>c.name==='files_compress'&&c.args.files.includes('endstone_endweave-0.4.3-py3-none-any.whl')));assert.equal((await prepareInstallation(weaveOld.client)).installation.status,'current');
const weaveNew=server();await installOnMCSV(weaveNew.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);
weaveNew.files.delete('/plugins/'+BUNDLED.name);weaveNew.files.set('/plugins/endstone_endweave-0.6.0-cp312-abi3-manylinux_2_28_x86_64.whl',Buffer.from('newer-weave'));
const newPlan=await prepareInstallation(weaveNew.client);assert.equal(newPlan.installation.parts.endweave,'newer');assert.equal(newPlan.installation.status,'current');
const beforeNew=weaveNew.calls.length;await installOnMCSV(weaveNew.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655,reinstall:true},async()=>fixture);
assert(weaveNew.files.has('/plugins/endstone_endweave-0.6.0-cp312-abi3-manylinux_2_28_x86_64.whl'));assert(!weaveNew.files.has('/plugins/'+BUNDLED.name));assert(!weaveNew.calls.slice(beforeNew).some(c=>c.name==='files_upload_base64'&&c.args.path.includes('endweave')));
// License state: a forged or missing license means the server is not current.
const forged=server();await installOnMCSV(forged.client,{serverId:'test-server',world:'Bedrock level',voicePort:18655},async()=>fixture);
const signed=JSON.parse(forged.files.get('/plugins/mumble_host/license.json'));forged.files.set('/plugins/mumble_host/license.json',JSON.stringify({...signed,users:500}));
assert.equal((await prepareInstallation(forged.client)).installation.parts.license,'invalid');assert.equal((await prepareInstallation(forged.client)).installation.status,'update');
forged.files.delete('/plugins/mumble_host/license.json');assert.equal((await prepareInstallation(forged.client)).installation.parts.license,'missing');
forged.files.set('/plugins/mumble_host/license.json',JSON.stringify({...signed,server:'deadbeef'}));assert.equal((await prepareInstallation(forged.client)).installation.parts.license,'invalid');
console.log('PASS endweave install: fresh install, old version replaced and backed up, newer kept, license valid/invalid/missing');

// Release selection: newest stable release in the series, with GitHub's published digest.
const asset=(v,extra={})=>({name:'endstone_endweave-'+v+'-cp312-abi3-manylinux_2_28_x86_64.whl',size:900000,digest:'sha256:'+'a'.repeat(64),browser_download_url:'https://github.com/EndstoneMC/endweave/releases/download/v'+v+'/endstone_endweave-'+v+'-cp312-abi3-manylinux_2_28_x86_64.whl',...extra});
const releases=[{assets:[asset('0.6.0')]},{prerelease:true,assets:[asset('0.5.9')]},{assets:[asset('0.5.3',{digest:undefined})]},{assets:[asset('0.5.2'),{...asset('0.5.2'),name:'endstone_endweave-0.5.2-cp312-abi3-win_amd64.whl'}]},{assets:[asset('0.5.4',{browser_download_url:'https://evil.example/x.whl'})]},{assets:[asset('0.5.5',{size:9000000})]}];
assert.deepEqual(pickRelease(releases,[0,5]).version,[0,5,2]);assert.deepEqual(pickRelease(releases,[0,6]).version,[0,6,0]);assert.equal(pickRelease(releases,[0,7]),null);
resetEndweaveCache();assert.equal(await latestEndweave({request:async()=>{throw Error('offline');}}),BUNDLED);
resetEndweaveCache();assert.deepEqual((await latestEndweave({request:async()=>({ok:true,json:async()=>releases})})).version,[0,5,2]);
resetEndweaveCache();assert.equal(await latestEndweave({request:async()=>({ok:true,json:async()=>[{assets:[asset('0.5.0')]}]})}),BUNDLED,'never older than the bundled copy');
resetEndweaveCache();assert.deepEqual((await latestEndweave({env:{ENDWEAVE_SERIES:'0.6'},request:async()=>({ok:true,json:async()=>releases})})).version,[0,6,0]);
// Download failure falls back to the bundled copy; a tampered download is rejected.
resetEndweaveCache();const remote={...pickRelease(releases,[0,5])};
const fallback=await loadEndweave(remote,{request:async()=>({ok:false})});assert.equal(fallback.info,BUNDLED);assert.equal(createHash('sha256').update(fallback.bytes).digest('hex'),BUNDLED.sha256);
await assert.rejects(endweaveBytes(remote,{request:async()=>({ok:true,arrayBuffer:async()=>Buffer.alloc(900000)})}),e=>e.code==='artifact_integrity');
console.log('PASS endweave releases: series lock, digest required, prerelease/foreign/oversized skipped, offline and download fallback, tamper rejected');
