import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const s=fs.readFileSync(new URL('../addon/BP/scripts/main.js',import.meta.url),'utf8');let players=[],tick,form,held=new Map(),calls=[];
class Form{constructor(){form=this;this.buttons=[];}button(label,action){this.buttons.push({label,action});return this;}closeButton(){return this;}show(){return new Promise(r=>this.done=r);}close(){this.done();}}
const player=(id,x)=>({id,isValid:true,location:{x,y:0,z:0},dimension:{id:'overworld'},messages:[],animations:[],sendMessage(m){this.messages.push(m);},playAnimation(a){this.animations.push(a);}});const a=player('a',0),b=player('b',3),c=player('c',2);players=[a,b,c];for(const p of players)held.set(p.id,p.id);
const ctx=vm.createContext({CustomForm:Form,world:{getAllPlayers:()=>players},system:{runInterval:f=>tick=f},heldPhoneData:p=>({id:held.get(p.id)}),readBankAccount:id=>({number:{a:'100',b:'200',c:'300'}[id]}),showBankTransfer:async(p,n,valid,target)=>calls.push({valid,target})});vm.runInContext(s.slice(s.indexOf('const touchpadReceivers'),s.indexOf('// ATM uses the PIN')),ctx);
async function receive(p,number){const pending=ctx.showTouchpad(p,{phoneId:p.id,number},()=>true);form.buttons[1].action();assert.equal(await pending,true);}
await receive(b,'200');assert.equal(ctx.nearbyTouchpads(a).length,1);const count=b.animations.length;tick();tick();assert.equal(b.animations.length,count);assert.equal(b.animations.at(-1),'animation.sleepybank.touchpad_receive');let pending=ctx.showTouchpad(a,{phoneId:'a',number:'100'},()=>true);form.buttons[0].action();await pending;assert.equal(calls[0].target,'200');assert(calls[0].valid());b.location.x=3.01;assert(!calls[0].valid());b.location.x=3;
await receive(c,'300');pending=ctx.showTouchpad(a,{phoneId:'a',number:'100'},()=>true);form.buttons[0].action();await new Promise(r=>setImmediate(r));assert.deepEqual(form.buttons.map(b=>b.label),['บัญชี 200','บัญชี 300']);form.buttons[1].action();await pending;assert.equal(calls[1].target,'300');held.set(c.id,'different');tick();assert.equal(ctx.nearbyTouchpads(a).length,1);assert.equal(c.messages.at(-1),'[ SleepBank ] ทัชแพดรับเงินถูกยกเลิก');assert(!calls[1].valid());b.dimension.id='nether';assert.equal(ctx.nearbyTouchpads(a).length,0);
console.log('PASS touchpad: receive, right arm request, 3-block boundary, multi-account selection, dimension filter, swapped phone cancellation and confirmation authorization');

const animations=JSON.parse(fs.readFileSync(new URL('../addon/RP/animations/sleepybank_touchpad.animation.json',import.meta.url),'utf8')).animations;assert.equal(animations['animation.sleepybank.touchpad_receive'].loop,true);assert.deepEqual(Object.keys(animations['animation.sleepybank.touchpad_receive'].bones),['rightarm']);
