import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../addon/BP/scripts/main.js',import.meta.url),'utf8');
const jobs=[], processed=[], warnings=[];
let players=[{id:'a'},{id:'b'},{id:'c'}], snapshots=0;
const ctx=vm.createContext({Date,console:{warn:m=>warnings.push(m)},system:{currentTick:0,runInterval:(f,n)=>jobs.push({f,n})}});
vm.runInContext(source.slice(source.indexOf('function staggerPlayerWork('),source.indexOf('staggerPlayerWork("inventory_maintenance"')),ctx);
ctx.staggerPlayerWork('test',100,()=>{snapshots++;return [...players];},p=>{processed.push(p.id);if(p.id==='b')throw Error('player left');});
const enqueue=jobs.find(j=>j.n===100).f, drain=jobs.find(j=>j.n===1).f;
enqueue(); drain(); assert.deepEqual(processed,['a']);
enqueue(); assert.equal(snapshots,1,'overlapping cycles must coalesce');
drain(); drain(); drain(); assert.deepEqual(processed,['a','b','c']);
assert.equal(warnings.length,1,'one invalid player must not block the pass');
players=[{id:'new'}]; enqueue(); drain(); drain(); assert.deepEqual(processed,['a','b','c','new']);
assert.equal(snapshots,2);
const pending=new Map(), messages=[], sounds=[];
let fail=false;
const phone=id=>({typeId:'phone',getDynamicProperty:()=>id});
const player={id:'owner',inv:{size:3,getItem:i=>[phone('a'),phone('a'),phone('b')][i]},sendMessage:m=>messages.push(m),playSound:s=>sounds.push(s)};
const bank=vm.createContext({inventory:p=>p.inv,isPhoneId:t=>t==='phone',PHONE_PROP_ID:'id',readBankAccount:id=>({number:id}),readPhoneHistoryStore:k=>pending.get(k)||[],writePhoneHistoryStore:(k,v)=>{if(fail)throw Error('disk failure');pending.set(k,v);}});
vm.runInContext(source.slice(source.indexOf('const bankNotificationCursor'),source.indexOf('async function showBankHistory')),bank);
const rows=n=>Array.from({length:n},(_,i)=>({amount:i+1,senderName:'sender'}));
pending.set('sleepybank:pending:a',rows(10));pending.set('sleepybank:pending:b',rows(1));
bank.deliverBankNotificationsForPlayer(player);
assert.equal(messages.length,4);assert.equal(pending.get('sleepybank:pending:a').length,6);
bank.deliverBankNotificationsForPlayer(player);
assert.equal(messages.length,8);assert.ok(messages[4].includes('1'),'next phone must get a turn');
assert.equal(pending.get('sleepybank:pending:b').length,0);
bank.deliverBankNotificationsForPlayer(player);assert.equal(messages.length,11);
bank.deliverBankNotificationsForPlayer(player);assert.equal(messages.length,11,'no duplicate delivery');
assert.equal(sounds.length,11);
pending.set('sleepybank:pending:a',rows(5));fail=true;
assert.throws(()=>bank.deliverBankNotificationsForPlayer(player));
assert.equal(messages.length,11);assert.equal(pending.get('sleepybank:pending:a').length,5,'failed persistence must retain notifications');
fail=false;bank.deliverBankNotificationsForPlayer({...player,id:'reconnected'});
assert.equal(messages.length,15);assert.equal(pending.get('sleepybank:pending:a').length,1);
let micJob, micInterval; const micStates=[];
const mic=vm.createContext({world:{getAllPlayers:()=>players},evaluate:p=>micStates.push(p.id),console,system:{runInterval:(f,n)=>{micJob=f;micInterval=n;}}});
vm.runInContext(source.slice(source.indexOf('// One-tick evaluation'),source.indexOf('// Snapshot each cycle')),mic);
assert.equal(micInterval,1);micJob();micJob();
assert.deepEqual(micStates,['new','new'],'mic evaluation must run for every player every tick');
assert.ok(source.includes('staggerPlayerWork("bank_notifications", 40'));
console.log('PASS: one player per tick, coalescing, leave/join isolation, bounded durable notifications, fairness, duplicate phones, write failures and reconnect.');

let writes=0; const locked={get lockMode(){return 'inventory';},set lockMode(v){writes++;},get keepOnDeath(){return true;},set keepOnDeath(v){writes++;}};
const unlocked={get lockMode(){return 'none';},set lockMode(v){writes++;},get keepOnDeath(){return false;},set keepOnDeath(v){writes++;}};
let slot=locked;
const flags=vm.createContext({inventory:()=>({size:1,getItem:()=>({typeId:'mic'}),getSlot:()=>slot}),isMicId:id=>id==='mic',ItemLockMode:{inventory:'inventory'}});
vm.runInContext(source.slice(source.indexOf('function reassertMicFlags('),source.indexOf('function publishMicState(')),flags);
flags.reassertMicFlags({});assert.equal(writes,0,'already locked mic needs no repeated item writes');
slot=unlocked;flags.reassertMicFlags({});assert.equal(writes,2,'missing flags must still be repaired');
