import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../addon/BP/scripts/main.js',import.meta.url),'utf8');
const data=new Map();let fail='',forms=[],players=[];let formsData=[];
class Obs{constructor(v){this.v=v;}getData(){return this.v;}setData(v){this.v=v;}}
class Form{constructor(){forms.push(this);this.buttons=[];this.fields=[];}header(){return this;}label(v){this.info=v;return this;}button(l,a,o){this.buttons.push({l,a,o});return this;}textField(l,v){this.fields.push(v);return this;}toggle(l,v){this.manual=v;return this;}slider(l,v){this.selected=v;return this;}closeButton(){return this;}show(){return new Promise(r=>this.finish=r);}close(){this.finish();}}
class Action{constructor(){this.buttons=[];}title(v){this.t=v;return this;}body(v){this.b=v;return this;}button(v){this.buttons.push(v);return this;}async show(){formsData.push(this);return responses.shift()??{canceled:true};}}
let responses=[];
const world={getDynamicProperty:k=>data.get(k),getDynamicPropertyIds:()=>[...data.keys()],setDynamicProperty(k,v){if(fail&&k===fail){fail='';throw Error('injected');}if(v===undefined)data.delete(k);else data.set(k,v);},getPlayers:()=>players};
const jobs=new Map();const profiles={a:{icName:'Sam'},b:{icName:'Receiver'}};const ctx=vm.createContext({world,BANK_ACCOUNT_PREFIX:'sleepybank:account:',readPhoneProfile:id=>profiles[id],CustomForm:Form,ActionFormData:Action,ObservableString:Obs,ObservableBoolean:Obs,ObservableNumber:Obs,system:{runInterval:f=>{jobs.set(1,f);return 1;},clearRun:id=>jobs.delete(id),runTimeout:f=>f()},console,formatPhoneMessageTime:t=>'date '+t,inventory:p=>p.inv,isPhoneId:id=>id==='phone',PHONE_PROP_ID:'id'});
vm.runInContext(source.slice(source.indexOf('function readPhoneHistoryStore('),source.indexOf('function readPhoneDeleted(')),ctx);
vm.runInContext(source.slice(source.indexOf('function readBankAccount('),source.indexOf('function migrateBankAccount(')),ctx);
vm.runInContext(source.slice(source.indexOf('const bankTransferPlayers'),source.indexOf('async function openAtm(')),ctx);
const player={id:'sender',sounds:[],playSound(s){this.sounds.push(s);},messages:[],sendMessage(m){this.messages.push(m.replace(/§./g,""));}};let allowed=true;
function reset(){data.clear();ctx.writeBankAccount({number:'123',phoneId:'a',balance:500,cardType:'black'});ctx.writeBankAccount({number:'456',phoneId:'b',balance:100,cardType:'white'});allowed=true;}
reset();let r=ctx.transferBankMoney(player,'123','456',200,()=>allowed);assert.ok(r.row);assert.equal(ctx.bankByNumber('123').balance,300);assert.equal(ctx.bankByNumber('123').expenses,200);assert.equal(ctx.bankByNumber('456').balance,300);assert.equal(ctx.bankByNumber('456').income,200);assert.equal(ctx.bankHistory('123').length,1);assert.equal(ctx.bankHistory('456').length,1);
for(const [target,amount,auth] of [['123',1,true],['999',1,true],['456',301,true],['456',0,true],['456',1.5,true],['456',1,false]])assert.ok(ctx.transferBankMoney(player,'123',target,amount,()=>auth).error);
const receiver={inv:{size:1,getItem:()=>({typeId:'phone',getDynamicProperty:()=> 'b'})},sounds:[],playSound(s){this.sounds.push(s);},messages:[],sendMessage(m){this.messages.push(m.replace(/§./g,""));}};players.forEach(p => ctx.deliverBankNotificationsForPlayer(p));assert.equal(receiver.messages.length,0);players=[receiver];players.forEach(p => ctx.deliverBankNotificationsForPlayer(p));assert.equal(receiver.messages[0],'[ SleepyBank ] คุณได้รับเงินจำนวน 200 จาก Sam');players.forEach(p => ctx.deliverBankNotificationsForPlayer(p));assert.equal(receiver.messages.length,1);
for(const key of ['sleepybank:account:456','sleepybank:history:456','sleepybank:pending:456']){reset();const before=JSON.stringify([...data]);fail=key;assert.ok(ctx.transferBankMoney(player,'123','456',50,()=>true).error);assert.equal(JSON.stringify([...data].sort()),JSON.stringify(JSON.parse(before).sort()));}
reset();const pending=ctx.showBankTransfer(player,'123',()=>allowed);let f=forms.at(-1);f.fields[0].setData('456');f.manual.setData(true);f.fields[1].setData('999');jobs.get(1)();assert.equal(f.fields[1].getData(),'500');f.buttons[0].a();await new Promise(r=>setImmediate(r));f=forms.at(-1);assert.ok(f.buttons[0].l.includes('ยืนยัน'));f.buttons[1].a();await new Promise(r=>setImmediate(r));f=forms.at(-1);assert.equal(f.fields[0].getData(),'456');assert.equal(f.fields[1].getData(),'500');f.fields[1].setData('50');f.buttons[0].a();await new Promise(r=>setImmediate(r));f=forms.at(-1);f.buttons[0].a();f.buttons[0].a();await pending;assert.equal(ctx.bankByNumber('123').balance,450);assert.equal(ctx.bankHistory('123').length,1);assert.equal(jobs.size,0);
for(let i=0;i<10;i++)ctx.transferBankMoney(player,'123','456',1,()=>true);responses=[{selection:8},{selection:3},{selection:8},{canceled:true}];await ctx.showBankHistory(player,'123',()=>true);assert.equal(formsData[0].buttons.length,10);assert.match(formsData[1].b,/หน้า 2/);
console.log('PASS: transfer conservation/income/expenses, validation, failure rollback, queued notification once, confirmation/back preserves input, duplicate submit guard and paged ActionForm history.');

assert.equal(player.sounds[0],'sleepybank.pay_success');assert.deepEqual(receiver.sounds,['sleepybank.receive']);
const defs=JSON.parse(fs.readFileSync(new URL('../addon/RP/sounds/sound_definitions.json',import.meta.url))).sound_definitions;for(const name of ['pay_success','receive']){assert.equal(defs['sleepybank.'+name].category,'ui');assert.ok(fs.existsSync(new URL('../addon/RP/'+defs['sleepybank.'+name].sounds[0].name+'.ogg',import.meta.url)));}assert.ok(!source.includes('ชื่อ IC ผู้รับ:'));console.log('PASS: sender/recipient sounds, no repeated receive sound, sound assets and recipient label.');
