import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from '../web/join/node_modules/jsdom/lib/api.js';
const html=await readFile(new URL('../web/join/install.html',import.meta.url),'utf8');const script=await readFile(new URL('../web/join/install.js',import.meta.url),'utf8');
async function page(plan){
 const dom=new JSDOM(html,{url:'https://sleepyvoice-join.vercel.app/install',runScripts:'outside-only'});const w=dom.window;const requests=[];let tick=null;w.setInterval=fn=>{tick=fn;return 1;};w.clearInterval=()=>{tick=null;};
 w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.latticeLoader=(node)=>{node.hidden=false;return {label(){},finish(state,text){node.textContent=text;}};};
 w.fetch=async(url,options)=>{const body=JSON.parse(options.body);requests.push({url,body});return {ok:true,json:async()=>url==='/api/payments/verify'?{paid:true}:JSON.parse(JSON.stringify(plan))};};
 w.eval(script);w.document.getElementById('mcsv-key').value='mcsv_private_test';
 w.document.getElementById('mcsv-form').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,5));return {dom,w,requests,tick:()=>tick?.(),el:id=>w.document.getElementById(id)};
}
const base={compatible:true,installAllowed:true,server:{id:'server',name:'Server'},world:'world',ports:[18655,20000],voicePort:18655};
const checkout={required:true,paid:false,status:'pending',orderId:'12345678-1234-1234-1234-123456789abc',amountSatang:25000,expiresAt:new Date(Date.now()+1800000).toISOString(),methods:{promptpay:true,truemoney:true},receiver:'Test Receiver',truemoneyPhone:'0933402606',promptpayId:'0812345678',qr:'data:image/png;base64,test'};
const p=await page({...base,payment:checkout});assert(p.w.document.querySelector('main.page').hidden);assert(!p.el('payment-page').hidden);assert(!p.el('install-dialog').open);assert.equal(p.el('payment-amount').textContent,'250');assert(!p.el('promptpay-fields').hidden);assert(p.el('truemoney-fields').hidden);
const radio=p.w.document.querySelector('input[value="truemoney"]');radio.checked=true;radio.dispatchEvent(new p.w.Event('change'));assert(p.el('promptpay-fields').hidden);assert(!p.el('truemoney-fields').hidden);
assert.equal(p.el('truemoney-target').textContent,'0933402606');assert.equal(p.el('truemoney-receiver'),null);assert.equal(p.el('payment-receiver'),null);assert(p.w.document.body.classList.contains('paying'));assert(p.el('payment-slip').required);assert.equal(p.el('payment-voucher'),null);
Object.defineProperty(p.el('payment-slip'),'files',{value:[new p.w.File([new Uint8Array([255,216,255,0])],'wallet.jpg',{type:'image/jpeg'})]});p.el('payment-form').dispatchEvent(new p.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,25));assert(p.el('install-dialog').open);assert(p.el('payment-form').hidden);assert.equal(p.requests.length,2);assert.equal(p.requests[1].url,'/api/payments/verify');assert(!('apiKey' in p.requests[1].body));assert(!('voucher' in p.requests[1].body));assert.equal(p.requests[1].body.method,'truemoney');assert.equal(p.requests[1].body.image,'/9j/AA==');assert.equal(p.requests.filter(r=>r.body.action==='install').length,0);
p.dom.window.close();
for(const payment of [{required:false},{required:true,paid:true}]){const p=await page({...base,payment});assert(p.el('payment-page').hidden);assert(p.el('install-dialog').open);p.dom.window.close();}
const unsupported=await page({compatible:false,server:{name:'Java'}});assert(unsupported.el('payment-page').hidden);assert(!unsupported.el('reinstall-help').hidden);unsupported.dom.window.close();
const review=await page({...base,payment:{...checkout,status:'review'}});assert(review.el('payment-form').hidden);assert(!review.el('payment-result').hidden);assert(!review.el('install-dialog').open);review.dom.window.close();
const one=await page({...base,payment:{...checkout,methods:{promptpay:false,truemoney:true},qr:null}});assert(one.el('method-promptpay').hidden);assert(!one.el('truemoney-fields').hidden);one.dom.window.close();
const pp=await page({...base,payment:checkout});Object.defineProperty(pp.el('payment-slip'),'files',{value:[new pp.w.File([new Uint8Array([255,216,255,0])],'bank.jpg',{type:'image/jpeg'})]});pp.el('payment-form').dispatchEvent(new pp.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,25));assert(pp.el('install-dialog').open);assert.equal(pp.requests[1].body.method,'promptpay');pp.dom.window.close();
console.log('PASS payment UI: Endstone check → payment → port, method switching, no premature install, no API-key forwarding, paid/free paths, unsupported/review states');

const weave={version:'0.5.1',name:'endstone_endweave-0.5.1-cp312-abi3-manylinux_2_28_x86_64.whl',source:'github',project:'https://github.com/EndstoneMC/endweave'};
const newest={plugin:'0.6.1',addon:'2.15.44',endweave:weave};
const latest=await page({...base,installation:{present:true,status:'current',parts:{plugin:'current',addon:'current',endweave:'current',license:'valid'},pluginVersions:['0.6.1'],addonVersions:{behavior:'2.15.44',resource:'2.15.44'},endweaveVersions:['0.5.1'],latest:newest},payment:{required:false,reason:'installed'}});
// An installed server first shows its status card; nothing opens on its own.
assert(!latest.el('install-status').hidden);assert.equal(latest.el('install-status-title').textContent,'เซิร์ฟเวอร์เป็นเวอร์ชันล่าสุดแล้ว');assert.equal(latest.el('install-status-action').textContent,'ติดตั้งซ้ำ');
const rows=[...latest.el('install-status-list').children].map(li=>li.textContent);assert.equal(rows.length,4);assert.match(rows[0],/ถูกต้อง/);assert.match(rows[3],/Endweave✔ 0\.5\.1 ล่าสุด/);assert.equal(latest.el('endweave-link').href,'https://github.com/EndstoneMC/endweave');
assert(!latest.el('reinstall-dialog').open);assert(!latest.el('install-dialog').open);assert(latest.el('payment-page').hidden);
latest.el('install-status-action').click();assert(latest.el('reinstall-dialog').open);assert.match(latest.el('installed-version').textContent,/Endweave 0\.5\.1/);
latest.el('keep-installed').click();assert(!latest.el('reinstall-dialog').open);assert(!latest.el('install-dialog').open);assert.equal(latest.requests.length,1);
latest.el('install-status-action').click();latest.el('confirm-reinstall').click();assert(latest.el('install-dialog').open);assert.match(latest.el('install-what').textContent,/MumbleHost 0\.6\.1 \+ Item Mic 2\.15\.44 \+ Endweave 0\.5\.1/);latest.dom.window.close();
const update=await page({...base,installation:{present:true,status:'update',parts:{plugin:'update',addon:'current',endweave:'absent',license:'missing'},pluginVersions:['0.6.0'],addonVersions:{behavior:'2.15.44'},endweaveVersions:[],latest:newest},payment:{required:false,reason:'installed'}});
assert.equal(update.el('install-status-title').textContent,'มีรุ่นใหม่ · แนะนำให้อัปเดต');assert.equal(update.el('install-status-action').textContent,'อัปเดตเป็นรุ่นล่าสุด');
const updateRows=[...update.el('install-status-list').children].map(li=>li.className+':'+li.textContent);assert.match(updateRows[0],/^warn:.*ยังไม่มี/);assert.match(updateRows[1],/^warn:MumbleHost0\.6\.0 → 0\.6\.1/);assert.match(updateRows[3],/^warn:Endweaveยังไม่มี → 0\.5\.1/);
assert(!update.el('install-dialog').open);update.el('install-status-action').click();assert(update.el('install-dialog').open);assert(!update.el('reinstall-dialog').open);assert(update.el('payment-page').hidden);update.dom.window.close();
const admin=await page({...base,installation:{present:false,status:'absent',parts:{plugin:'absent',addon:'absent',endweave:'absent',license:'missing'},pluginVersions:[],addonVersions:{},endweaveVersions:[],latest:newest},payment:{required:false,reason:'admin'}});
assert(admin.el('payment-page').hidden,'admin skips checkout');assert(admin.el('install-dialog').open);assert.match(admin.el('check-result').textContent,/บัญชีแอดมิน ติดตั้งฟรี/);admin.dom.window.close();
console.log('PASS installation UI: status card (license/MumbleHost/Item Mic/Endweave), latest offers reinstall, cancellation does nothing, old version recommends update without checkout');

const countdown=await page({...base,payment:{...checkout,expiresAt:new Date(Date.now()+60000).toISOString()}});assert.match(countdown.el('payment-expiry').textContent,/เหลือเวลาชำระ (59|60) วินาที/);assert(!html.includes('ตรวจด้วย SlipOK'));const now=countdown.w.Date.now;countdown.w.Date.now=()=>now()+30000;countdown.tick();assert.match(countdown.el('payment-expiry').textContent,/เหลือเวลาชำระ (29|30) วินาที/);countdown.w.Date.now=()=>now()+61000;countdown.tick();assert.match(countdown.el('payment-expiry').textContent,/หมดเวลาชำระ/);assert(countdown.el('payment-submit').disabled);countdown.el('payment-form').dispatchEvent(new countdown.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,5));assert.equal(countdown.requests.length,1);countdown.el('payment-back').click();assert(!countdown.w.document.body.classList.contains('paying'));countdown.dom.window.close();console.log('PASS countdown: seconds decrease against expiry, expired checkout blocks submission, back exits full-screen payment');
