import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source = fs.readFileSync('addon/BP/scripts/main.js', 'utf8');
const jobs = new Map(); let next = 0, ringing = false;
const played = [], stopped = [];
const player = {id:'p', playSound:s=>played.push(s), runCommand:s=>stopped.push(s)};
const ctx = vm.createContext({system:{currentTick:0,runTimeout:(fn,ticks)=>{jobs.set(++next,{fn,ticks});return next;},clearRun:id=>jobs.delete(id)},phoneCallFor:()=>ringing?{state:'ringing'}:undefined,callPlayer:()=>player,phoneRingtone:()=> 'deltarune'});
vm.runInContext(source.slice(source.indexOf('const ringtonePreviews'),source.indexOf('function endPhoneCall')),ctx);
ctx.previewRingtone(player,'deltarune');
assert.equal(jobs.get(next).ticks,100); jobs.get(next).fn();
assert.match(stopped.at(-1),/deltarune$/);
ctx.previewRingtone(player,'undertale'); assert.equal(jobs.get(next).ticks,21);
const stopCount = stopped.length; jobs.get(next).fn(); assert.equal(stopped.length,stopCount);
ctx.previewRingtone(player,'your_phone_linging'); assert.equal(jobs.get(next).ticks,327);
const prior = next; ctx.previewRingtone(player,'deltarune'); assert.equal(jobs.has(prior),false);
assert.match(stopped.at(-1),/your_phone_linging$/);
const preview = next; const call={b:'p',phoneB:'phone',state:'ringing'};
ctx.playPhoneRingtone(call); assert.equal(jobs.has(preview),false); assert.equal(call.nextRingTick,502);
ringing=true; const playCount=played.length; ctx.previewRingtone(player,'undertale'); assert.equal(played.length,playCount);
console.log('PASS: previews, switching cancellation, five-second Deltarune cutoff and incoming-call isolation.');
