(()=>{
 const el=id=>document.getElementById(id),dialog=el('guide-dialog');
 document.querySelectorAll('[data-guide]').forEach(button=>button.addEventListener('click',()=>{const api=button.dataset.guide==='api';el('api-guide').hidden=!api;el('reinstall-guide').hidden=api;el('guide-title').textContent=api?'วิธีหา MCSV API Key':'ติดตั้งใหม่เป็น Endstone';dialog.showModal();}));
 el('close-guide').addEventListener('click',()=>dialog.close());
 el('show-key').addEventListener('click',()=>{const show=el('mcsv-key').type==='password';el('mcsv-key').type=show?'text':'password';el('show-key').textContent=show?'ซ่อน':'แสดง';el('show-key').setAttribute('aria-pressed',String(show));el('show-key').setAttribute('aria-label',show?'ซ่อน API Key':'แสดง API Key');});
 let plan=null,busy=false;const setup=el('install-dialog');
 const errors={timeout:'MCSV ตอบกลับช้าเกินกำหนด กรุณาลองใหม่',endpoint:'ไม่พบ endpoint ของ MCSV กรุณาติดต่อผู้ดูแล SleepyMumla',rejected:'MCSV ปฏิเสธคำขอ กรุณาลองใหม่หรือติดต่อผู้ดูแล',upstream:'บริการ MCSV ตอบกลับผิดพลาด กรุณาลองใหม่ภายหลัง',invalid_response:'MCSV ส่งข้อมูลกลับมาไม่ถูกต้อง กรุณาลองใหม่',auth_check_unavailable:'ตรวจสอบสมาชิก Discord ไม่สำเร็จ กรุณาลองใหม่หรือเข้าสู่ระบบใหม่',format:'รูปแบบคำขอไม่ถูกต้อง กรุณารีเฟรชหน้าแล้วลองใหม่',invalid_key:'API Key ไม่ถูกต้องหรือถูกยกเลิกแล้ว กรุณาสร้าง Key ใหม่จาก MCSV',permission:'Key นี้ไม่มีสิทธิ์อ่านข้อมูลเซิร์ฟเวอร์ แก้สิทธิ์ที่ ระบบ → API / MCP แล้วลองใหม่',installing:'เซิร์ฟเวอร์กำลังติดตั้ง รอให้เสร็จแล้วตรวจอีกครั้ง',rate_limit:'ตรวจสอบถี่เกินไป กรุณารอสักครู่แล้วลองใหม่',unverified:'ยืนยันประเภทเซิร์ฟเวอร์ไม่ได้ กรุณาตรวจข้อมูลใน MCSV แล้วลองใหม่',unavailable:'เชื่อมต่อ MCSV ไม่สำเร็จ กรุณาลองอีกครั้งภายหลัง',auth_unavailable:'ระบบเข้าสู่ระบบยังไม่พร้อม กรุณาลองใหม่ภายหลัง'};
 Object.assign(errors,{backup_failed:'สำรองไฟล์ก่อนติดตั้งไม่สำเร็จ ระบบยังไม่ได้เปลี่ยนไฟล์ติดตั้ง กรุณาลองใหม่หรือติดต่อผู้ดูแล',permission:'Key นี้ไม่มีสิทธิ์ติดตั้ง กรุณาเปิดสิทธิ์อ่านข้อมูลเซิร์ฟเวอร์ อ่านไฟล์ จัดการไฟล์ และ Restart ที่ ระบบ → API / MCP',server_inactive:'เซิร์ฟเวอร์ไม่พร้อมใช้งาน กรุณาตรวจสถานะหรือวันหมดอายุใน MCSV',unsafe_layout:'โครงสร้างไฟล์เซิร์ฟเวอร์ไม่รองรับการติดตั้งอัตโนมัติ กรุณาติดต่อผู้ดูแล',world_missing:'ไม่พบโลกที่ระบุใน server.properties เปิดเซิร์ฟเวอร์เพื่อสร้างโลกหนึ่งครั้ง แล้วตรวจใหม่',no_voice_port:'ไม่มีพอร์ตเพิ่มเติมสำหรับเสียง กรุณาขอพอร์ตเพิ่มจาก MCSV',server_running:'เซิร์ฟเวอร์กำลังเปลี่ยนสถานะ กรุณารอจนเปิดหรือปิดเสร็จแล้วลองใหม่',server_changed:'ข้อมูลเซิร์ฟเวอร์หรือโลกเปลี่ยนไป กรุณาปิดคู่มือและตรวจสอบใหม่',invalid_port:'พอร์ตเสียงนี้ไม่ได้จัดสรรให้เซิร์ฟเวอร์ กรุณาตรวจใหม่',busy:'มีการติดตั้งอยู่แล้ว กรุณารอให้เสร็จ',duplicate_pack:'พบแอดออน UUID เดียวกันหลายโฟลเดอร์ กรุณาจัดการแพ็กซ้ำก่อนติดตั้ง',existing_version:'พบ Item Mic คนละเวอร์ชัน ระบบจะไม่ทับแพ็กเดิม กรุณาติดต่อผู้ดูแลเพื่ออัปเดต',existing_plugin:'พบไฟล์ MumbleHost คนละเวอร์ชัน กรุณาสำรองและจัดการเวอร์ชันเก่าก่อนติดตั้ง',invalid_pack_list:'ไฟล์แพ็กของโลกอ่านไม่ได้ ระบบหยุดเพื่อรักษาข้อมูลเดิม',invalid_config:'ไฟล์ตั้งค่าปลั๊กอินไม่ถูกต้อง กรุณาติดต่อผู้ดูแล',artifact_unavailable:'ดาวน์โหลดไฟล์ติดตั้งไม่สำเร็จ กรุณาลองอีกครั้ง',artifact_integrity:'ไฟล์ติดตั้งไม่ผ่านการตรวจสอบ ระบบหยุดติดตั้ง',verification_failed:'ตรวจไฟล์หลังติดตั้งไม่ผ่าน กรุณาตรวจสอบก่อนเปิดเซิร์ฟเวอร์',install_failed:'ติดตั้งไม่สำเร็จ กรุณาลองอีกครั้งหรือติดต่อผู้ดูแล'});
 async function api(body){const response=await fetch('/api/mcsv/install',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({...body,apiKey:el('mcsv-key').value.trim()})});const data=await response.json();if(!response.ok){const error=Error(data.error);Object.assign(error,{reference:data.reference,partial:data.partial});throw error;}return data;}
 function message(error){return (error.message==='login_required'?'เซสชันหมดอายุ กรุณาเข้าสู่ระบบด้วย Discord ใหม่':errors[error.message]||errors.unavailable)+(error.partial?' · มีไฟล์ติดตั้งบางส่วนแล้ว สามารถตรวจสถานะใน MCSV สามารถลองติดตั้งซ้ำเพื่อทำขั้นตอนที่เหลือได้':'')+(error.reference?' · รหัสตรวจสอบ '+error.reference:'');}
 function resetKey(){el('mcsv-key').value='';el('mcsv-key').type='password';el('show-key').textContent='แสดง';el('show-key').setAttribute('aria-pressed','false');el('show-key').setAttribute('aria-label','แสดง API Key');}
 Object.assign(errors,{status_expired:'หมดเวลารอ กรุณาตรวจสถานะเซิร์ฟเวอร์ใน MCSV',voice_failed:'ติดตั้งไฟล์แล้ว แต่ระบบเสียงเริ่มทำงานไม่สำเร็จ กรุณาตรวจ Console ใน MCSV'});
 let installed=null;
 function portDialog(){el('install-server').textContent=plan.server.name+' · โลก '+plan.world;el('voice-port').replaceChildren(...plan.ports.map(port=>{const option=document.createElement('option');option.value=String(port);option.textContent=String(port);option.selected=port===plan.voicePort;return option;}));el('install-result').hidden=true;el('install-form').hidden=false;setup.showModal();}
 el('mcsv-key').addEventListener('input',()=>{plan=null;installed=null;});
 el('close-install').addEventListener('click',()=>{if(!busy)setup.close();});setup.addEventListener('cancel',event=>{if(busy)event.preventDefault();});
 async function waitForVoice(loader){loader.label('กำลัง Restart และเตรียมระบบเสียง');const deadline=Date.now()+14*60*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,5000));const status=await api({action:'status'});if(status.ready){loader.finish('done','ระบบเสียงพร้อมใช้งาน กำลังไปหน้า Join');resetKey();window.location.assign(status.joinUrl);return;}loader.label(status.stage==='voice_starting'?'กำลังเตรียมระบบเสียง':'กำลังรอเซิร์ฟเวอร์เปิด');}throw Error('status_expired');}
 el('install-form').addEventListener('submit',async event=>{event.preventDefault();if(!plan||busy)return;busy=true;el('install-submit').disabled=true;el('close-install').disabled=true;el('check-server').disabled=true;el('mcsv-key').readOnly=true;el('voice-port').disabled=true;const loader=latticeLoader(el('install-result'),'กำลังสำรองไฟล์และติดตั้ง');try{if(!installed){installed=await api({action:'install',confirm:true,serverId:plan.server.id,world:plan.world,voicePort:Number(el('voice-port').value)});if(installed.installed!==true)throw Error('verification_failed');}await waitForVoice(loader);}catch(error){loader.finish('error',message(error));if(installed)el('install-submit').textContent='ตรวจความพร้อมอีกครั้ง';}finally{busy=false;el('install-submit').disabled=false;el('close-install').disabled=false;el('check-server').disabled=false;el('mcsv-key').readOnly=false;el('voice-port').disabled=Boolean(installed);}});
 el('mcsv-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const button=el('check-server');button.disabled=true;const loader=latticeLoader(el('check-result'),'กำลังตรวจสอบเซิร์ฟเวอร์');el('reinstall-help').hidden=true;try{plan=null;installed=null;const data=await api({action:'prepare'});if(data.compatible===true&&data.installAllowed){plan=data;loader.finish('done',data.server.name+' · Minecraft Bedrock · Endstone');el('install-submit').textContent='ใช้พอร์ตนี้';el('voice-port').disabled=false;portDialog();}else if(data.compatible){throw Error('permission');}else{loader.finish('error','เซิร์ฟเวอร์นี้ไม่รองรับ กรุณาติดตั้งใหม่เป็น Minecraft Bedrock · Endstone');el('reinstall-help').hidden=false;}}catch(error){loader.finish('error',message(error));}finally{button.disabled=false;if(!plan)resetKey();}});
})();
