(()=>{
 const el=id=>document.getElementById(id),dialog=el('guide-dialog');
 document.querySelectorAll('[data-guide]').forEach(button=>button.addEventListener('click',()=>{const api=button.dataset.guide==='api';el('api-guide').hidden=!api;el('reinstall-guide').hidden=api;el('guide-title').textContent=api?'วิธีหา MCSV API Key':'ติดตั้งใหม่เป็น Endstone';dialog.showModal();}));
 el('close-guide').addEventListener('click',()=>dialog.close());
 el('show-key').addEventListener('click',()=>{const show=el('mcsv-key').type==='password';el('mcsv-key').type=show?'text':'password';el('show-key').textContent=show?'ซ่อน':'แสดง';el('show-key').setAttribute('aria-pressed',String(show));el('show-key').setAttribute('aria-label',show?'ซ่อน API Key':'แสดง API Key');});
 let plan=null,busy=false,reinstallConfirmed=false;const setup=el('install-dialog');const reinstallDialog=el('reinstall-dialog');
 function nextInstallation(){if(plan.installation?.status==='current'&&!reinstallConfirmed){const v=plan.installation.latest;el('installed-version').textContent=plan.server.name+' · MumbleHost '+v.plugin+' · Item Mic '+v.addon+' · Endweave '+(plan.installation.endweaveVersions.at(-1)||v.endweave.version);reinstallDialog.showModal();}else portDialog();}
 function statusRow(name,[tone,text]){const item=document.createElement('li');item.className=tone;const label=document.createElement('span');label.textContent=name;const value=document.createElement('span');value.textContent=text;item.append(label,value);return item;}
 function showStatus(){const i=plan.installation,p=i.parts,l=i.latest,box=el('install-status');const current=i.status==='current';
  const was=(list,fallback)=>list.length?list.join(', '):fallback;
  const rows=[['ใบอนุญาต',p.license==='valid'?['ok','✔ ถูกต้อง · ผูกกับเซิร์ฟเวอร์นี้']:p.license==='unknown'?['info','ตรวจไม่ได้ในตอนนี้']:['warn',p.license==='missing'?'ยังไม่มี · ออกให้ตอนอัปเดต':'ไม่ถูกต้อง · ออกใหม่ตอนอัปเดต']],
   ['MumbleHost',p.plugin==='current'?['ok','✔ '+l.plugin+' ล่าสุด']:['warn',was(i.pluginVersions,'ยังไม่มี')+' → '+l.plugin]],
   ['Item Mic',p.addon==='current'?['ok','✔ '+l.addon+' ล่าสุด']:['warn',was([...new Set(Object.values(i.addonVersions))],'ยังไม่มี')+' → '+l.addon]],
   ['Endweave',p.endweave==='current'?['ok','✔ '+l.endweave.version+' ล่าสุด']:p.endweave==='newer'?['ok','✔ '+i.endweaveVersions.join(', ')+' (ใหม่กว่า)']:['warn',was(i.endweaveVersions,'ยังไม่มี')+' → '+l.endweave.version]]];
  el('install-status-title').textContent=current?'เซิร์ฟเวอร์เป็นเวอร์ชันล่าสุดแล้ว':'มีรุ่นใหม่ · แนะนำให้อัปเดต';
  el('install-status-list').replaceChildren(...rows.map(row=>statusRow(...row)));
  el('endweave-link').href=l.endweave.project;
  el('install-status-action').textContent=current?'ติดตั้งซ้ำ':'อัปเดตเป็นรุ่นล่าสุด';
  box.classList.toggle('is-current',current);box.classList.toggle('is-update',!current);box.hidden=false;}
 el('install-status-action').addEventListener('click',()=>{if(plan&&!busy)nextInstallation();});
 el('confirm-reinstall').addEventListener('click',()=>{reinstallConfirmed=true;reinstallDialog.close();portDialog();});
 for(const id of ['cancel-reinstall','keep-installed'])el(id).addEventListener('click',()=>reinstallDialog.close());
 const errors={timeout:'MCSV ตอบกลับช้าเกินกำหนด กรุณาลองใหม่',endpoint:'ไม่พบ endpoint ของ MCSV กรุณาติดต่อผู้ดูแล SleepyMumla',rejected:'MCSV ปฏิเสธคำขอ กรุณาลองใหม่หรือติดต่อผู้ดูแล',upstream:'บริการ MCSV ตอบกลับผิดพลาด กรุณาลองใหม่ภายหลัง',invalid_response:'MCSV ส่งข้อมูลกลับมาไม่ถูกต้อง กรุณาลองใหม่',auth_check_unavailable:'ตรวจสอบสมาชิก Discord ไม่สำเร็จ กรุณาลองใหม่หรือเข้าสู่ระบบใหม่',format:'รูปแบบคำขอไม่ถูกต้อง กรุณารีเฟรชหน้าแล้วลองใหม่',invalid_key:'API Key ไม่ถูกต้องหรือถูกยกเลิกแล้ว กรุณาสร้าง Key ใหม่จาก MCSV',permission:'Key นี้ไม่มีสิทธิ์อ่านข้อมูลเซิร์ฟเวอร์ แก้สิทธิ์ที่ ระบบ → API / MCP แล้วลองใหม่',installing:'เซิร์ฟเวอร์กำลังติดตั้ง รอให้เสร็จแล้วตรวจอีกครั้ง',rate_limit:'ตรวจสอบถี่เกินไป กรุณารอสักครู่แล้วลองใหม่',unverified:'ยืนยันประเภทเซิร์ฟเวอร์ไม่ได้ กรุณาตรวจข้อมูลใน MCSV แล้วลองใหม่',unavailable:'เชื่อมต่อ MCSV ไม่สำเร็จ กรุณาลองอีกครั้งภายหลัง',auth_unavailable:'ระบบเข้าสู่ระบบยังไม่พร้อม กรุณาลองใหม่ภายหลัง'};
 Object.assign(errors,{backup_failed:'สำรองไฟล์ก่อนติดตั้งไม่สำเร็จ ระบบยังไม่ได้เปลี่ยนไฟล์ติดตั้ง กรุณาลองใหม่หรือติดต่อผู้ดูแล',permission:'Key นี้ไม่มีสิทธิ์ติดตั้ง กรุณาเปิดสิทธิ์อ่านข้อมูลเซิร์ฟเวอร์ อ่านไฟล์ จัดการไฟล์ และ Restart ที่ ระบบ → API / MCP',server_inactive:'เซิร์ฟเวอร์ไม่พร้อมใช้งาน กรุณาตรวจสถานะหรือวันหมดอายุใน MCSV',unsafe_layout:'โครงสร้างไฟล์เซิร์ฟเวอร์ไม่รองรับการติดตั้งอัตโนมัติ กรุณาติดต่อผู้ดูแล',world_missing:'ไม่พบโลกที่ระบุใน server.properties เปิดเซิร์ฟเวอร์เพื่อสร้างโลกหนึ่งครั้ง แล้วตรวจใหม่',no_voice_port:'ไม่มีพอร์ตเพิ่มเติมสำหรับเสียง กรุณาขอพอร์ตเพิ่มจาก MCSV',server_running:'เซิร์ฟเวอร์กำลังเปลี่ยนสถานะ กรุณารอจนเปิดหรือปิดเสร็จแล้วลองใหม่',server_changed:'ข้อมูลเซิร์ฟเวอร์หรือโลกเปลี่ยนไป กรุณาปิดคู่มือและตรวจสอบใหม่',invalid_port:'พอร์ตเสียงนี้ไม่ได้จัดสรรให้เซิร์ฟเวอร์ กรุณาตรวจใหม่',busy:'มีการติดตั้งอยู่แล้ว กรุณารอให้เสร็จ',duplicate_pack:'พบแอดออน UUID เดียวกันหลายโฟลเดอร์ กรุณาจัดการแพ็กซ้ำก่อนติดตั้ง',existing_version:'อ่านเวอร์ชันระบบเดิมไม่ได้ กรุณาติดต่อผู้ดูแล',existing_plugin:'พบไฟล์ MumbleHost คนละเวอร์ชัน กรุณาสำรองและจัดการเวอร์ชันเก่าก่อนติดตั้ง',invalid_pack_list:'ไฟล์แพ็กของโลกอ่านไม่ได้ ระบบหยุดเพื่อรักษาข้อมูลเดิม',invalid_config:'ไฟล์ตั้งค่าปลั๊กอินไม่ถูกต้อง กรุณาติดต่อผู้ดูแล',newer_version:'เซิร์ฟเวอร์ใช้รุ่นใหม่กว่าที่ตัวติดตั้งรองรับ ระบบหยุดเพื่อป้องกันการลดเวอร์ชัน',reinstall_confirmation:'เซิร์ฟเวอร์ใช้รุ่นล่าสุดแล้ว กรุณาตรวจใหม่และยืนยันติดตั้งซ้ำก่อน',artifact_unavailable:'ดาวน์โหลดไฟล์ติดตั้งไม่สำเร็จ กรุณาลองอีกครั้ง',artifact_integrity:'ไฟล์ติดตั้งไม่ผ่านการตรวจสอบ ระบบหยุดติดตั้ง',verification_failed:'ตรวจไฟล์หลังติดตั้งไม่ผ่าน กรุณาตรวจสอบก่อนเปิดเซิร์ฟเวอร์',install_failed:'ติดตั้งไม่สำเร็จ กรุณาลองอีกครั้งหรือติดต่อผู้ดูแล',license_unavailable:'ระบบสิทธิ์ใช้งานยังไม่พร้อม กรุณาติดต่อผู้ดูแล SleepyMumla'});
 async function api(body){const response=await fetch('/api/mcsv/install',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({...body,apiKey:el('mcsv-key').value.trim()})});let data;try{data=await response.json();}catch{data={error:response.status===504?'gateway_timeout':'unavailable',partial:body.action==='install'};}if(!response.ok){const error=Error(data.error);Object.assign(error,{reference:data.reference,partial:data.partial});throw error;}return data;}
 function message(error){return (error.message==='login_required'?'เซสชันหมดอายุ กรุณาเข้าสู่ระบบด้วย Discord ใหม่':errors[error.message]||errors.unavailable)+(error.partial?' · มีไฟล์ติดตั้งบางส่วนแล้ว สามารถตรวจสถานะใน MCSV สามารถลองติดตั้งซ้ำเพื่อทำขั้นตอนที่เหลือได้':'')+(error.reference?' · รหัสตรวจสอบ '+error.reference:'');}
 function resetKey(){el('mcsv-key').value='';el('mcsv-key').type='password';el('show-key').textContent='แสดง';el('show-key').setAttribute('aria-pressed','false');el('show-key').setAttribute('aria-label','แสดง API Key');}
 Object.assign(errors,{install_timeout:'การติดตั้งใช้เวลานานเกินไปจึงหยุดกลางทาง กดตรวจสอบเซิร์ฟเวอร์แล้วติดตั้งอีกครั้งเพื่อทำส่วนที่เหลือ ไม่ต้องชำระเงินซ้ำ',gateway_timeout:'การเชื่อมต่อหมดเวลาระหว่างติดตั้ง กดตรวจสอบเซิร์ฟเวอร์แล้วติดตั้งอีกครั้ง ไม่ต้องชำระเงินซ้ำ',busy:'มีการติดตั้งเซิร์ฟเวอร์นี้อยู่แล้ว รอประมาณ 5 นาทีแล้วลองใหม่',payment_retry:'ระบบตรวจสลิปเชื่อมต่อไม่ได้ชั่วคราว ยังไม่ได้ตัดสลิปนี้ กรุณาส่งสลิปเดิมอีกครั้งใน 1–2 นาที'});
 Object.assign(errors,{status_expired:'หมดเวลารอ กรุณาตรวจสถานะเซิร์ฟเวอร์ใน MCSV',voice_failed:'ติดตั้งไฟล์แล้ว แต่ระบบเสียงเริ่มทำงานไม่สำเร็จ กรุณาตรวจ Console ใน MCSV'});
 let installed=null,paymentTimer=null;
 function stopPaymentTimer(){if(paymentTimer!==null){clearInterval(paymentTimer);paymentTimer=null;}}
 function updatePaymentCountdown(){if(!plan?.payment||plan.payment.paid||plan.payment.status!=='pending'||el('payment-page').hidden)return;const seconds=Math.max(0,Math.ceil((new Date(plan.payment.expiresAt).getTime()-Date.now())/1000));el('payment-expiry').textContent=seconds>0?'เหลือเวลาชำระ '+seconds.toLocaleString('th-TH')+' วินาที':'หมดเวลาชำระ · กรุณาตรวจสอบเซิร์ฟเวอร์ใหม่';el('payment-expiry').classList.toggle('expired',seconds===0);el('payment-submit').disabled=busy||seconds===0;if(seconds===0)stopPaymentTimer();}
 window.addEventListener('pagehide',stopPaymentTimer);document.addEventListener('visibilitychange',updatePaymentCountdown);
 function paymentMethod(){const method=document.querySelector('input[name="payment-method"]:checked')?.value;el('promptpay-fields').hidden=method!=='promptpay';el('truemoney-fields').hidden=method!=='truemoney';el('payment-slip').required=true;}
 function fitPayment(){const card=document.querySelector('.payment-card'),page=el('payment-page');if(page.hidden||!page.clientHeight)return;card.style.transform='scale('+Math.min(1,(page.clientHeight-24)/card.scrollHeight)+')';}if(window.ResizeObserver)new ResizeObserver(fitPayment).observe(document.querySelector('.payment-card'));window.addEventListener('resize',fitPayment);window.visualViewport?.addEventListener('resize',fitPayment);function paymentPage(){const p=plan.payment;document.querySelector('main.page').hidden=true;el('payment-page').hidden=false;document.body.classList.add('paying');el('payment-server').textContent=plan.server.name+' · Minecraft Bedrock · Endstone';el('payment-amount').textContent=(p.amountSatang/100).toLocaleString('th-TH',{maximumFractionDigits:2});el('payment-order').textContent='คำสั่งซื้อ '+p.orderId;stopPaymentTimer();el('payment-expiry').classList.remove('expired');el('payment-expiry').textContent=p.status==='pending'?'':'รายการนี้อยู่ระหว่างตรวจสอบ';el('payment-result').hidden=true;el('payment-form').reset();for(const method of ['promptpay','truemoney']){const label=el('method-'+method);label.hidden=!p.methods[method];label.querySelector('input').disabled=!p.methods[method];}document.querySelector('input[name="payment-method"]:not(:disabled)').checked=true;if(p.qr){el('payment-qr').src=p.qr;el('payment-target').textContent=p.promptpayId;}el('truemoney-target').textContent=p.truemoneyPhone||'';paymentMethod();el('payment-form').hidden=p.status!=='pending';if(p.status!=='pending'){const loader=latticeLoader(el('payment-result'),'กำลังตรวจสอบรายการ');loader.finish('error',errors.payment_review);}updatePaymentCountdown();if(p.status==='pending'&&new Date(p.expiresAt).getTime()>Date.now())paymentTimer=setInterval(updatePaymentCountdown,1000);window.scrollTo(0,0);fitPayment();}
 document.querySelectorAll('input[name="payment-method"]').forEach(input=>input.addEventListener('change',paymentMethod));
 el('payment-back').addEventListener('click',()=>{if(busy)return;stopPaymentTimer();el('payment-page').hidden=true;document.body.classList.remove('paying');document.querySelector('main.page').hidden=false;plan=null;});
 Object.assign(errors,{payment_unavailable:'ระบบชำระเงินยังไม่พร้อม กรุณาติดต่อผู้ดูแล',payment_required:'กรุณาชำระค่าติดตั้งสำหรับเซิร์ฟเวอร์นี้ก่อน',payment_order:'ไม่พบคำสั่งซื้อของคุณ กรุณาตรวจเซิร์ฟเวอร์ใหม่',payment_expired:'คำสั่งซื้อหมดอายุ กรุณาตรวจเซิร์ฟเวอร์ใหม่ หากโอนแล้วให้ติดต่อผู้ดูแล',payment_review:'ต้องตรวจสอบรายการนี้เพิ่มเติม กรุณาติดต่อผู้ดูแลพร้อมรหัสคำสั่งซื้อ อย่าชำระซ้ำ',payment_duplicate:'สลิปนี้ถูกใช้แล้ว หากเป็นรายการของคุณให้ติดต่อผู้ดูแล',payment_amount:'ยอดเงินไม่ตรงกับค่าติดตั้ง',payment_receiver:'บัญชีผู้รับเงินไม่ตรง กรุณาตรวจชื่อบัญชี',payment_method:'ช่องทางชำระเงินนี้ยังไม่พร้อม',payment_rate_limit:'ตรวจสอบถี่เกินไป กรุณารอ 10 นาที',slip_format:'กรุณาแนบรูป JPG, PNG หรือ WEBP ไม่เกิน 2 MB',slip_invalid:'ตรวจสลิปไม่ผ่าน กรุณาใช้สลิปโอนเงินจริง',slip_delay:'ธนาคารยังไม่พร้อมตรวจสลิป กรุณารอ 10 นาทีแล้วลองอีกครั้ง'});
 async function imageBase64(file){if(!file||file.size>2000000||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('slip_format');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('slip_format'));reader.readAsDataURL(file);});}
 el('payment-form').addEventListener('submit',async event=>{event.preventDefault();if(busy||!plan?.payment?.orderId)return;if(new Date(plan.payment.expiresAt).getTime()<=Date.now()){updatePaymentCountdown();return;}busy=true;el('payment-submit').disabled=true;el('payment-back').disabled=true;const loader=latticeLoader(el('payment-result'),'กำลังตรวจสอบการชำระเงิน');try{const method=document.querySelector('input[name="payment-method"]:checked').value;const body={orderId:plan.payment.orderId,method};body.image=await imageBase64(el('payment-slip').files[0]);const response=await fetch('/api/payments/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const data=await response.json();if(!response.ok){const error=Error(data.error);error.reference=data.reference;throw error;}if(data.paid!==true)throw Error('payment_review');plan.payment.paid=true;stopPaymentTimer();el('payment-form').hidden=true;el('payment-expiry').textContent='ชำระสำเร็จแล้ว';el('payment-slip').value='';loader.finish('done','ชำระสำเร็จ เลือกพอร์ตเพื่อเริ่มติดตั้ง');portDialog();}catch(error){loader.finish('error',message(error));}finally{busy=false;el('payment-submit').disabled=false;el('payment-back').disabled=false;updatePaymentCountdown();}});
 function portDialog(){const l=plan.installation?.latest;el('install-server').textContent=plan.server.name+' · โลก '+plan.world;if(l)el('install-what').textContent='ติดตั้ง MumbleHost '+l.plugin+' + Item Mic '+l.addon+' + Endweave '+l.endweave.version+' และเปิดใช้แพ็กในโลกปัจจุบัน โดยรักษารายการแพ็กอื่นไว้';el('voice-port').replaceChildren(...plan.ports.map(port=>{const option=document.createElement('option');option.value=String(port);option.textContent=String(port);option.selected=port===plan.voicePort;return option;}));el('install-result').hidden=true;el('install-form').hidden=false;setup.showModal();}
 el('mcsv-key').addEventListener('input',()=>{plan=null;installed=null;el('install-status').hidden=true;});
 el('close-install').addEventListener('click',()=>{if(!busy)setup.close();});setup.addEventListener('cancel',event=>{if(busy)event.preventDefault();});
 async function waitForVoice(loader){loader.label('กำลัง Restart และเตรียมระบบเสียง');const deadline=Date.now()+14*60*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,5000));const status=await api({action:'status'});if(status.ready){loader.finish('done','ระบบเสียงพร้อมใช้งาน กำลังไปหน้า Join');resetKey();rememberOwnedLink(status.joinUrl);window.location.assign(status.joinUrl);return;}loader.label(status.stage==='voice_starting'?'กำลังเตรียมระบบเสียง':'กำลังรอเซิร์ฟเวอร์เปิด');}throw Error('status_expired');}
 el('install-form').addEventListener('submit',async event=>{event.preventDefault();if(!plan||busy)return;busy=true;el('install-submit').disabled=true;el('close-install').disabled=true;el('check-server').disabled=true;el('mcsv-key').readOnly=true;el('voice-port').disabled=true;const loader=latticeLoader(el('install-result'),'กำลังสำรองไฟล์และติดตั้ง');try{if(!installed){installed=await api({action:'install',confirm:true,serverId:plan.server.id,world:plan.world,voicePort:Number(el('voice-port').value),reinstall:reinstallConfirmed});if(installed.installed!==true)throw Error('verification_failed');}await waitForVoice(loader);}catch(error){loader.finish('error',message(error));if(installed)el('install-submit').textContent='ตรวจความพร้อมอีกครั้ง';}finally{busy=false;el('install-submit').disabled=false;el('close-install').disabled=false;el('check-server').disabled=false;el('mcsv-key').readOnly=false;el('voice-port').disabled=Boolean(installed);}});
 el('mcsv-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const button=el('check-server');button.disabled=true;const loader=latticeLoader(el('check-result'),'กำลังตรวจสอบเซิร์ฟเวอร์');el('reinstall-help').hidden=true;el('install-status').hidden=true;try{plan=null;installed=null;reinstallConfirmed=false;const data=await api({action:'prepare'});if(data.compatible===true&&data.installAllowed){plan=data;loader.finish('done',data.server.name+' · Minecraft Bedrock · Endstone'+(data.installation?.present?' · พบระบบเดิม':''));el('install-submit').textContent='ใช้พอร์ตนี้';el('voice-port').disabled=false;if(plan.payment?.required&&!plan.payment.paid)paymentPage();else if(plan.installation?.present)showStatus();else nextInstallation();}else if(data.compatible){throw Error('permission');}else{loader.finish('error','เซิร์ฟเวอร์นี้ไม่รองรับ กรุณาติดตั้งใหม่เป็น Minecraft Bedrock · Endstone');el('reinstall-help').hidden=false;}}catch(error){loader.finish('error',message(error));}finally{button.disabled=false;if(!plan)resetKey();}});
})();
// The join page shows its share panel only where this marker exists: the browser that installed.
function rememberOwnedLink(joinUrl){try{const uri=decodeURIComponent(new URL(joinUrl,location.origin).hash.slice(1)).toLowerCase(),key='sleepy-owned-links';const list=JSON.parse(localStorage.getItem(key)||'[]').filter(item=>item!==uri);list.unshift(uri);localStorage.setItem(key,JSON.stringify(list.slice(0,10)));}catch{}}
