(()=>{
 const el=id=>document.getElementById(id),dialog=el('guide-dialog');
 document.querySelectorAll('[data-guide]').forEach(button=>button.addEventListener('click',()=>{const api=button.dataset.guide==='api';el('api-guide').hidden=!api;el('reinstall-guide').hidden=api;el('guide-title').textContent=api?'วิธีหา MCSV API Key':'ติดตั้งใหม่เป็น Endstone';dialog.showModal();}));
 el('close-guide').addEventListener('click',()=>dialog.close());
 el('show-key').addEventListener('click',()=>{const show=el('mcsv-key').type==='password';el('mcsv-key').type=show?'text':'password';el('show-key').textContent=show?'ซ่อน':'แสดง';el('show-key').setAttribute('aria-pressed',String(show));el('show-key').setAttribute('aria-label',show?'ซ่อน API Key':'แสดง API Key');});
 let plan=null,busy=false;const setup=el('install-dialog');
 const errors={timeout:'MCSV ตอบกลับช้าเกินกำหนด กรุณาลองใหม่',endpoint:'ไม่พบ endpoint ของ MCSV กรุณาติดต่อผู้ดูแล SleepyMumla',rejected:'MCSV ปฏิเสธคำขอ กรุณาลองใหม่หรือติดต่อผู้ดูแล',upstream:'บริการ MCSV ตอบกลับผิดพลาด กรุณาลองใหม่ภายหลัง',invalid_response:'MCSV ส่งข้อมูลกลับมาไม่ถูกต้อง กรุณาลองใหม่',auth_check_unavailable:'ตรวจสอบสมาชิก Discord ไม่สำเร็จ กรุณาลองใหม่หรือเข้าสู่ระบบใหม่',format:'รูปแบบคำขอไม่ถูกต้อง กรุณารีเฟรชหน้าแล้วลองใหม่',invalid_key:'API Key ไม่ถูกต้องหรือถูกยกเลิกแล้ว กรุณาสร้าง Key ใหม่จาก MCSV',permission:'Key นี้ไม่มีสิทธิ์อ่านข้อมูลเซิร์ฟเวอร์ แก้สิทธิ์ที่ ระบบ → API / MCP แล้วลองใหม่',installing:'เซิร์ฟเวอร์กำลังติดตั้ง รอให้เสร็จแล้วตรวจอีกครั้ง',rate_limit:'ตรวจสอบถี่เกินไป กรุณารอสักครู่แล้วลองใหม่',unverified:'ยืนยันประเภทเซิร์ฟเวอร์ไม่ได้ กรุณาตรวจข้อมูลใน MCSV แล้วลองใหม่',unavailable:'เชื่อมต่อ MCSV ไม่สำเร็จ กรุณาลองอีกครั้งภายหลัง',auth_unavailable:'ระบบเข้าสู่ระบบยังไม่พร้อม กรุณาลองใหม่ภายหลัง'};
 Object.assign(errors,{backup_failed:'สำรองไฟล์ก่อนติดตั้งไม่สำเร็จ ระบบยังไม่ได้เปลี่ยนไฟล์ติดตั้ง กรุณาลองใหม่หรือติดต่อผู้ดูแล',permission:'Key นี้ไม่มีสิทธิ์ติดตั้ง กรุณาเปิดสิทธิ์อ่านข้อมูลเซิร์ฟเวอร์ อ่านไฟล์ และจัดการไฟล์ที่ ระบบ → API / MCP',server_inactive:'เซิร์ฟเวอร์ไม่พร้อมใช้งาน กรุณาตรวจสถานะหรือวันหมดอายุใน MCSV',unsafe_layout:'โครงสร้างไฟล์เซิร์ฟเวอร์ไม่รองรับการติดตั้งอัตโนมัติ กรุณาติดต่อผู้ดูแล',world_missing:'ไม่พบโลกที่ระบุใน server.properties เปิดเซิร์ฟเวอร์เพื่อสร้างโลกหนึ่งครั้ง แล้วปิดก่อนตรวจใหม่',no_voice_port:'ไม่มีพอร์ตเพิ่มเติมสำหรับเสียง กรุณาขอพอร์ตเพิ่มจาก MCSV',server_running:'เซิร์ฟเวอร์ยังเปิดอยู่ กรุณาปิดที่ Console ของ MCSV แล้วลองติดตั้งอีกครั้ง',server_changed:'ข้อมูลเซิร์ฟเวอร์หรือโลกเปลี่ยนไป กรุณาปิดคู่มือและตรวจสอบใหม่',invalid_port:'พอร์ตเสียงนี้ไม่ได้จัดสรรให้เซิร์ฟเวอร์ กรุณาตรวจใหม่',busy:'มีการติดตั้งอยู่แล้ว กรุณารอให้เสร็จ',duplicate_pack:'พบแอดออน UUID เดียวกันหลายโฟลเดอร์ กรุณาจัดการแพ็กซ้ำก่อนติดตั้ง',existing_version:'พบ Item Mic คนละเวอร์ชัน ระบบจะไม่ทับแพ็กเดิม กรุณาติดต่อผู้ดูแลเพื่ออัปเดต',existing_plugin:'พบไฟล์ MumbleHost คนละเวอร์ชัน กรุณาสำรองและจัดการเวอร์ชันเก่าก่อนติดตั้ง',invalid_pack_list:'ไฟล์แพ็กของโลกอ่านไม่ได้ ระบบหยุดเพื่อรักษาข้อมูลเดิม',invalid_config:'ไฟล์ตั้งค่าปลั๊กอินไม่ถูกต้อง กรุณาติดต่อผู้ดูแล',artifact_unavailable:'ดาวน์โหลดไฟล์ติดตั้งไม่สำเร็จ กรุณาลองอีกครั้ง',artifact_integrity:'ไฟล์ติดตั้งไม่ผ่านการตรวจสอบ ระบบหยุดติดตั้ง',verification_failed:'ตรวจไฟล์หลังติดตั้งไม่ผ่าน กรุณาตรวจสอบก่อนเปิดเซิร์ฟเวอร์',install_failed:'ติดตั้งไม่สำเร็จ กรุณาลองอีกครั้งหรือติดต่อผู้ดูแล'});
 async function api(body){const response=await fetch('/api/mcsv/install',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({...body,apiKey:el('mcsv-key').value.trim()})});const data=await response.json();if(!response.ok){const error=Error(data.error);Object.assign(error,{reference:data.reference,partial:data.partial});throw error;}return data;}
 function message(error){return (error.message==='login_required'?'เซสชันหมดอายุ กรุณาเข้าสู่ระบบด้วย Discord ใหม่':errors[error.message]||errors.unavailable)+(error.partial?' · มีไฟล์ติดตั้งบางส่วนแล้ว ยังไม่ต้องเปิดเซิร์ฟเวอร์ สามารถลองติดตั้งซ้ำเพื่อทำขั้นตอนที่เหลือได้':'')+(error.reference?' · รหัสตรวจสอบ '+error.reference:'');}
 function resetKey(){el('mcsv-key').value='';el('mcsv-key').type='password';el('show-key').textContent='แสดง';el('show-key').setAttribute('aria-pressed','false');el('show-key').setAttribute('aria-label','แสดง API Key');}
 el('mcsv-key').addEventListener('input',()=>{plan=null;el('install-ready').hidden=true;});
 el('open-install').addEventListener('click',()=>{if(!plan)return;el('install-server').textContent=plan.server.name+' · โลก '+plan.world;el('voice-port').replaceChildren(...plan.ports.map(port=>{const option=document.createElement('option');option.value=String(port);option.textContent=String(port);option.selected=port===plan.voicePort;return option;}));el('start-after').checked=false;el('start-after').disabled=!plan.canStart;el('install-confirm').checked=false;el('install-result').hidden=true;setup.showModal();});
 el('close-install').addEventListener('click',()=>{if(!busy)setup.close();});setup.addEventListener('cancel',event=>{if(busy)event.preventDefault();});
 el('install-form').addEventListener('submit',async event=>{event.preventDefault();if(!plan||busy)return;busy=true;el('install-submit').disabled=true;el('close-install').disabled=true;el('check-server').disabled=true;el('mcsv-key').readOnly=true;const result=el('install-result');result.hidden=false;result.className='check-result';result.textContent='กำลังดาวน์โหลด สำรองไฟล์ และติดตั้ง… กรุณาอย่าปิดหน้านี้หรือเปิดเซิร์ฟเวอร์ระหว่างติดตั้ง';try{const data=await api({action:'install',confirm:el('install-confirm').checked,serverId:plan.server.id,world:plan.world,voicePort:Number(el('voice-port').value),start:el('start-after').checked});if(data.installed!==true)throw Error('verification_failed');result.classList.add('success');result.textContent='✓ ติดตั้งและตรวจไฟล์เรียบร้อย · พอร์ตเสียง '+data.voicePort+' · '+(data.started?'ส่งคำสั่งเปิดเซิร์ฟเวอร์แล้ว รอจน Console แสดง Mumble host started':'เปิดเซิร์ฟเวอร์ที่ Console ของ MCSV เพื่อเริ่มใช้งาน')+(data.backups?.length?' · สำรองไฟล์: '+data.backups.join(', '):data.backup?' · สำรองไฟล์: '+data.backup:'')+' · ในเกมใช้ /vcb ตรวจสถานะระบบเสียง';plan=null;el('install-ready').hidden=true;el('install-form').hidden=true;resetKey();}catch(error){result.classList.add('error');result.textContent=message(error);}finally{busy=false;el('install-submit').disabled=false;el('close-install').disabled=false;el('check-server').disabled=false;el('mcsv-key').readOnly=false;}});
 el('mcsv-form').addEventListener('submit',async event=>{
  event.preventDefault();const button=el('check-server'),result=el('check-result');button.disabled=true;result.hidden=false;result.className='check-result';result.textContent='กำลังตรวจสอบเซิร์ฟเวอร์…';el('reinstall-help').hidden=true;
  try{
   plan=null;el('install-ready').hidden=true;el('install-form').hidden=false;const data=await api({action:'prepare'});
   if(data.compatible===true){result.classList.add('success');result.textContent='✓ '+data.server.name+' เป็น Minecraft Bedrock · Endstone · '+(data.installAllowed?'โลก '+data.world+' · '+(data.state==='offline'?'พร้อมติดตั้ง':'ปิดเซิร์ฟเวอร์ที่ Console ก่อนติดตั้ง'):'Key นี้ยังขาดสิทธิ์ติดตั้ง กรุณาเปิดสิทธิ์อ่านและจัดการไฟล์ที่ API / MCP');if(data.installAllowed){plan=data;el('install-ready').hidden=false;}}
   else{result.classList.add('error');result.textContent='เซิร์ฟเวอร์นี้ไม่รองรับ ('+data.server.game+' / '+data.server.serverType+') กรุณาติดตั้งใหม่เป็น Minecraft Bedrock · Endstone';el('reinstall-help').hidden=false;}
  }catch(error){result.classList.add('error');result.textContent=message(error);}
  finally{button.disabled=false;if(!plan)resetKey();}
 });
})();
