// React Bits LatticeLoader orbit pattern, adapted for the site's vanilla JavaScript.
window.latticeLoader=(container,label)=>{
 container.hidden=false;container.replaceChildren();
 const row=document.createElement('div');row.className='lattice-loader';row.dataset.status='working';row.style.cssText='--ll-cell:6px;--ll-gap:2px;--ll-font:14px;--ll-idle:.15;--ll-peak:1;--ll-cycle:864ms;--ll-mark:#22c55e;--ll-ease-in-out:cubic-bezier(.77,0,.175,1);--ll-ease-out:cubic-bezier(.16,1,.3,1)';
 const grid=document.createElement('span');grid.className='lattice-loader__grid';grid.style.gridTemplateColumns='repeat(3,6px)';grid.setAttribute('aria-hidden','true');
 const layers=['run','mark'].map(kind=>{const layer=document.createElement('span');layer.className='lattice-loader__layer lattice-loader__'+kind;layer.style.gridTemplateColumns='repeat(3,6px)';for(let i=0;i<9;i++){const dot=document.createElement('span');dot.className='lattice-loader__cell';dot.style.borderRadius='50%';if(kind==='run'){const delay=[0,1,2,7,null,3,6,5,4][i];if(delay===null)dot.dataset.hole='';else dot.style.animationDelay=delay*108+'ms';}layer.append(dot);}grid.append(layer);return layer;});
 const text=document.createElement('span');text.className='lattice-loader__label';text.textContent=label;const timer=document.createElement('span');timer.className='lattice-loader__timer';timer.setAttribute('aria-hidden','true');const started=performance.now();const tick=()=>timer.textContent=((performance.now()-started)/1000).toFixed(1)+'s';tick();let interval=setInterval(tick,100);row.append(grid,text,timer);container.append(row);
 return {label:value=>text.textContent=value,finish:(status,message)=>{clearInterval(interval);tick();row.dataset.status=status;row.style.setProperty('--ll-mark',status==='done'?'#22c55e':'#ef4444');const cells=status==='done'?[2,3,5,7]:[0,2,4,6,8];[...layers[1].children].forEach((dot,i)=>{if(cells.includes(i))dot.dataset.on='';});text.textContent=status==='done'?'เสร็จใน':'หยุดหลัง';const detail=document.createElement('p');detail.textContent=message;container.append(detail);}};
};
